# DIRECTORIES FOR DATASET
BASE_PATH = "datasets/metro"
ORIGINAL_IMAGES_PATH = f"{BASE_PATH}/originals"
RESIZED_IMAGES_PATH = f"{BASE_PATH}/resized"
JPG_CONVERTED_IMAGES_PATH = f"{BASE_PATH}/jpgs"

METADATA_PATH = f"{BASE_PATH}/metadata"

REQUIRED_PATHS = [
    ORIGINAL_IMAGES_PATH,
    RESIZED_IMAGES_PATH,
    JPG_CONVERTED_IMAGES_PATH,
]

# URLS
BASE_URL = "https://www.metro.cdmx.gob.mx"
